- name: prod server docker install 
  hosts: _prod_server
  become: true
  vars: 
    aws_region: us-east-1
    aws_account_id: ""
    ecr_registry: "{{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
  tasks:
    - name: update all packages
      ansible.builtin.yum:
        name: '*'
        state: latest 

    - name: Getting AWS account id
      shell: aws sts get-caller-identity --query 'Account' --output text
      register: account_id

    - name: Assigning AWS account id to variable
      set_fact:
        aws_account_id: "{{ account_id.stdout }}"

    - name: Remove docker if installed from CentOS repo
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed

    - name: Install yum utils
      ansible.builtin.yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - unzip

    - name: Install Docker
      ansible.builtin.yum:
        name: docker
        state: latest


    - name: Add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes  
        
    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes 