---
- name: Setup single-node K3s cluster, install Kompose, Docker, and perform system update
  hosts: _prod_server
  become: true
  remote_user: ubuntu
  tasks:

    - name: Update and upgrade the system packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - apt-transport-https
        - ca-certificates
        - gnupg
        - lsb-release

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes

    - name: Install Docker Compose
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
      args:
        executable: /bin/bash

    - name: Add user to docker group to avoid sudo
      user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: true

    - name: Install K3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash

    - name: Verify K3s is running and node is ready
      command: kubectl get nodes
      register: node_check
      retries: 5
      delay: 5
      until: "'Ready' in node_check.stdout"

    - name: Set kubectl permissions and configure kubeconfig
      shell: |
        sudo chown $USER:$USER $(which kubectl)
        sudo chmod +x $(which kubectl)
        sudo chmod 644 /etc/rancher/k3s/k3s.yaml
        mkdir -p ~/.kube
        sudo cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
        sudo chown $(id -u):$(id -g) ~/.kube/config
        echo 'export KUBECONFIG=~/.kube/config' >> ~/.bashrc
      args:
        executable: /bin/bash

    - name: Source bashrc to use kubectl without sudo
      shell: source ~/.bashrc
      args:
        executable: /bin/bash

    - name: Install Kompose
      shell: |
        curl -L https://github.com/kubernetes/kompose/releases/download/v1.26.1/kompose-linux-amd64 -o /usr/local/bin/kompose
        chmod +x /usr/local/bin/kompose
      args:
        executable: /bin/bash

    - name: Verify kubectl, Kompose, and Docker installation
      command: kubectl get nodes
      register: kubectl_output


    - name: Get AWS ECR login password
      command: "aws ecr get-login-password --region {{ region }}"
      register: ecr_password
      changed_when: false

    - name: Log in to ECR Docker registry
      command: "docker login --username AWS --password-stdin {{ ecr_registry }}"
      args:
        stdin: "{{ ecr_password.stdout }}"
      changed_when: false

    - name: Create Kubernetes Docker registry secret
      command: >
        kubectl create secret docker-registry {{ secret_name }}
        --docker-server={{ ecr_registry }}
        --docker-username=AWS
        --docker-password={{ ecr_password.stdout }}
        --docker-email={{ docker_email }}
      register: kubectl_output
      changed_when: true
      ignore_errors: true

    - name: Show kubectl output
      debug:
        msg: "{{ kubectl_output.stdout }}"

    - debug:
        var: kubectl_output.stdout
