apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-secret: ecr-secret
    kompose.service.type: NodePort
    kompose.version: 1.29.0 (997957870)
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: app
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.image-pull-secret: ecr-secret
        kompose.service.type: NodePort
        kompose.version: 1.29.0 (997957870)
      creationTimestamp: null
      labels:
        io.kompose.network/task-4-carrental-net: "true"
        io.kompose.service: app
    spec:
      containers:
        - env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://db:5432/carrental
            - name: SPRING_DATASOURCE_USERNAME
              value: techprodb_user
          image: 058264318400.dkr.ecr.us-east-1.amazonaws.com/task-4-ecr-repo:backend
          name: brc-backend
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources: {}
      imagePullSecrets:
        - name: ecr-secret
      restartPolicy: Always
status: {}
