apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.image-pull-secret: ecr-secret
    kompose.service.type: NodePort
    kompose.version: 1.29.0 (997957870)
  labels:
    io.kompose.service: ui
  name: ui
spec:
  ports:
    - name: "3000"
      nodePort: 30001
      port: 3000
      targetPort: 3000
  selector:
    io.kompose.service: ui
  type: NodePort
